### ISSUE TITLE
keep coverage.info in CodeCoverage.cmake for further analysis

### ISSUE THREAD

**Issue by beku** [bilke/cmake-modules#13]
codecov.io fails with gcc's gcov files and works fine with coverage.info from lcov. However on line 151all coverage info files are removed, which is unfortunate. See here:
https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake#L151

My request is to keep the essential info file and not remove it. That way codecov.io can point to this very useful cmake file and work pretty easy with default instructions.

**Comment by fkromer** [comment]
As @beku pointed out some tools depend on the lcov info file. E.g. to beeing able to display the coverage in the [Atom IDE](https://atom.io/) with the plugin [lcov-info](https://atom.io/packages/lcov-info) the coverage information is assumed to reside in `coverage/lcov.info`...

(The line where the coverage info is removed moved to [line 157](https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake#L157) meanwhile.)

**Comment by bilke** [comment]
Please submit a pull request if you like.
