### ISSUE TITLE
Code comment for CodeCoverage.cmake is missleading

### ISSUE THREAD

**Issue by mjscosta** [bilke/cmake-modules#16]
Hi,

For test coverage the parameter
"Param _testrunner     The name of the target which runs the tests"
 is misleading, it is not the target but a command with arguments, in which for cmake via make generator would be something like "make test".

Is there a reason for not being a cmake target and added as a dependency ?
flexibility ? 

```cmake
...
# Param _testrunner     The name of the target which runs the tests.
#						MUST return ZERO always, even on errors.
#						If not, no coverage report will be created!
...
FUNCTION(SETUP_TARGET_FOR_COVERAGE _targetname _testrunner _outputname)
...
	SEPARATE_ARGUMENTS(test_command UNIX_COMMAND "${_testrunner}")

	# Setup target
	ADD_CUSTOM_TARGET(${_targetname}

		# Cleanup lcov
		${LCOV_PATH} --directory . --zerocounters

		# Run tests
		COMMAND ${test_command} ${ARGV3}
...
	)
```
Thanks

**Comment by bilke** [comment]
Hi @mjscosta,

thanks for your hint. I am sorry I did a bad job in updating these modules here.. meanwhile you can get [another version which uses named parameters](https://github.com/ufz/ogs/blob/master/scripts/cmake/cmake/CodeCoverage.cmake) which is more verbose in my opinion. I will try to merge both versions ..

**Comment by mjscosta** [comment]
Hi @bilke ,

Thanks!

**Comment by bilke** [comment]
@mjscosta I merged the linked version. From now on this repo will be the only version as it will be used as a git submodule in our main project: https://github.com/ufz/ogs/pull/1827
