### ISSUE TITLE
CodeCoverage.cmake syntax seems to changed

### ISSUE THREAD

**Issue by ddt-tdd** [bilke/cmake-modules#17]
I'm using cmake 3.5 (linux) and 3.7 (under CLion) with Catch. I wanted to use code coverage and stumble to your great integration, which I'll try to use to integrate in CLion.
When I used it with the description in beginning of the text I always had following error:

""" CMake Error at cmake-modules/CodeCoverage.cmake:179 (add_custom_command):
"""   add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.

I read your CodeCoverage.cmake and had to learn how arguments are parsed ;-). I had to change my call in the CMakeLists.txt to: 
setup_target_for_coverage(NAME ${PROJECT_TEST_NAME}_coverage
            EXECUTABLE ${PROJECT_TEST_NAME}
            DEPENDENCIES ${PROJECT_TEST_NAME})

Could you change the description in the beginning of the CodeCoverage.cmake.

**Comment by bilke** [comment]
@ddt-tdd I am sorry there were some old instructions. The new instructions were already there at the function definitions. I made this more clear with  88a98ee.
