### ISSUE TITLE
CodeCoverage: gcovr does not find anything in out of tree builds

### ISSUE THREAD

**Issue by arvedarved** [bilke/cmake-modules#25]
For some unknown reason a coverage of 0 was recorded, so I changed the gcovr invocation to include an --object-directory although according to gcovr manpage this should not be necessary.
<pre>
        # Running gcovr
        COMMAND ${GCOVR_PATH} -x -r ${CMAKE_SOURCE_DIR} ${COBERTURA_EXCLUDES}
            -o ${Coverage_NAME}.xml --object-directory=${CMAKE_BINARY_DIR}
</pre>

Now all .gc* files are found in my object directory.

**Comment by bilke** [comment]
Maybe this is because you have nested CMake `project()`-s? The working directory of the `gcovr`-call is set to `${PROJECT_BINARY_DIR}` which in this case would be different to `${CMAKE_BINARY_DIR}`.

**Comment by KindDragon** [comment]
Fixed in PR #29
