### ISSUE TITLE
should I copy the file as-is provided for my project?

### ISSUE THREAD

**Issue by addy1997** [bilke/cmake-modules#58]
Hi,
I want to monitor the code coverage of my Cmake-based project. Also, I was looking for files to monitor the built targets. Which files are suitable? Do I need to modify this [file](https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake) for my project?

Thanks

**Comment by bilke** [comment]
You do not need to modify. Just copy the CodeCoverage.cmake file into a directory which is in you CMake module search path and and call the appropriate functions from the module.
