### ISSUE TITLE
CodeCoverage triggers warning on Multi-Config Generators

### ISSUE THREAD

**Issue by globberwops** [bilke/cmake-modules#59]
https://github.com/bilke/cmake-modules/blob/d6d1a778e41cb114e5cdf279b8a659fa0ce9a0d4/CodeCoverage.cmake#L194
This line triggers a warning on Multi-Config Generators.

You could check if [GENERATOR_IS_MULTI_CONFIG](https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html) e.g.
```
get_property(MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(NOT CMAKE_BUILD_TYPE STREQUAL "Debug" AND NOT MULTI_CONFIG)
...
```

**Comment by bilke** [comment]
Pull requests are welcome!
