### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by antonioivanov6** [bilke/cmake-modules#62]
Hello.

When I called "make someCoverageTarget 127.0.0.1 1918", the command line parameters could not be passed to the application.
Even if i use the variable $ {EXECUTABLE_ARGS}, the effect is the same.
What could I do?

**Comment by bilke** [comment]
You simply cannot pass cli args via `make`.

Please note that `${EXECUTABLE_ARGS}` is a CMake variable, it has to be passed to CMake, **not** to make, e.g.:

```bash
cmake . -DEXECUTABLE_ARGS="127.0.0.1 1918"
make someCoverageTarget
```
